version: "3"
networks:
  shorturl-network:
    driver: bridge
services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./"
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - PGUSER=postgres
      - PGHOST=database
      - PGDATABASE=postgres
      - PGPASSWORD=root
      - PGPORT=5432
    networks:
      - shorturl-network
  database:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/
    restart: always
    networks:
      - shorturl-network
volumes:
  db-data:
