version: '3.8'

services:
  nestjs-app:
    image: node:22-alpine
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=nestjs_user
      - DATABASE_PASSWORD=nestjs_password
      - DATABASE_NAME=nestjs_db
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=nestjs_user
      - POSTGRES_PASSWORD=nestjs_password
      - POSTGRES_DB=nestjs_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
